INSERT INTO users(
                  username,
                  password,
                  first_name,
                  last_name,
                  email,
                  city,
                  role
) VALUES
      (
       'vitus',
       'NdnwajkdnAWd',
       'Виталий',
       'Головий',
       'Ndwad@mail.ru',
       'Брест',
       'ROLE_USER'
      ),
      (
       'dawdwa',
       'DWdawd',
       'Бутерброд',
       'Сколбосов',
       'dawd@dawd.com',
       'Кухня',
       'ROLE_USER'
      ),
      (
       'bombaster227',
       'shbebeib',
       'Тест',
       'Тестович',
       'test@test.test',
       'Нью-Тест',
       'ROLE_USER'
      )