version: '3.8'

services:
  app:
    build: ..
    container_name: app
    ports:
      - '8080:8080'
    restart: on-failure
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 3580
      MYSQL_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    container_name: db
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: 'demoapp'
      MYSQL_ROOT_PASSWORD: '3580'
    volumes:
      - .:/docker-entrypoint-initdb.d
      - /var/lib/mysql
    ports:
      - '3307:3306'